export const actionTypes = {
  SET_AUTHDATA: "SET_AUTHDATA",
  SET_PINCODE: "SET_PINCODE",
  SET_NOTIFICATION: "SET_NOTIFICATION",
  CLEAR_DATA: "CLEAR_DATA",
  UPDATE_CART: "UPDATE_CART",
  TOGGLE_CART: "TOGGLE_CART",
};
